version: '3.9'
services:
  coursehub-backend:
    build: .
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - abnet      
      
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - abnet      
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
    networks:
      - abnet      


  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - abnet

volumes:
  grafana-data:
  elasticsearch_data:
    driver: local

networks:
  abnet:
    driver: bridge